# Documentation: http://docs.travis-ci.com/user/languages/julia/

language: julia

os:
  - linux
  - osx

julia:
  - nightly
  - 1

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.5
      os: linux
      script:
        - julia --color=yes --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --color=yes --project=docs/ docs/make.jl
      after_success: skip

notifications:
  email: false
