# Documentation: http://docs.travis-ci.com/user/languages/julia/

language: julia

os:
  - linux
  - osx

julia:
  - 1
  - nightly

codecov: true
coveralls: true

notifications:
  email: false

jobs:
  # Uncomment the following lines to allow failures on nightly julia
  # (tests will run but not make your overall status red)
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
    - stage: "Documentation"
      julia: 1.6
      os: linux
      env:
        - GKSwstype="100"  # See https://github.com/jheinen/GR.jl/issues/278
      addons:
        apt:
          packages:
            # Use GR with Travis
            - libxt6
            - libxrender1
            - libxext6
            - libgl1-mesa-glx
            - libqt5widgets5
      script:
        - julia --color=yes --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --color=yes --project=docs/ docs/make.jl
      after_success: skip
