$(arg prefix)robotiq_2f_140_gripper_controller:
    type: position_controllers/GripperActionController
    joint: $(arg prefix)finger_joint
    action_monitor_rate: 100

gazebo_ros_control:
  pid_gains:
        $(arg prefix)finger_joint: {p: 10.0, i: 0.0, d: 0.01} 
        $(arg prefix)right_outer_knuckle_joint: {p: 10.0, i: 0.0, d: 0.00} 
        $(arg prefix)right_inner_knuckle_joint: {p: 10.0, i: 0.0, d: 0.01} 
        $(arg prefix)left_inner_knuckle_joint: {p: 10.0, i: 0.0, d: 0.01} 
        $(arg prefix)left_inner_finger_joint: {p: 0.5, i: 0.0, d: 0.001} 
        $(arg prefix)right_inner_finger_joint: {p: 0.5, i: 0.0, d: 0.001} 