sudo: required
dist: trusty
language: generic

services:
  - docker

env:
  matrix:
    - ROS_DISTRO=kinetic
    - ROS_DISTRO=melodic

script:
  - export SOURCE_PATH=$(pwd)
  - echo "Testing iiwa_stack on ROS '$ROS_DISTRO'"
  - docker pull ros:$ROS_DISTRO-robot > /dev/null
  - docker run -e SOURCE_PATH -v $(pwd):/root/iiwa_stack_ws/src -it ros:$ROS_DISTRO-robot /bin/bash -c "cd /root/iiwa_stack_ws/src; source .travis/ci.sh"
