controller_list:
  - name: m1n6s300
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - m1n6s300_joint_1
      - m1n6s300_joint_2
      - m1n6s300_joint_3
      - m1n6s300_joint_4
      - m1n6s300_joint_5
      - m1n6s300_joint_6      
  - name: m1n6s300_gripper
    action_ns: gripper_command
    type: GripperCommand
    default: true    
    joints:
      - m1n6s300_joint_finger_1
      - m1n6s300_joint_finger_2
      - m1n6s300_joint_finger_3
