joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: "$(arg prefix)gen3_joint_trajectory_controller"
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - $(arg prefix)joint_1
      - $(arg prefix)joint_2
      - $(arg prefix)joint_3
      - $(arg prefix)joint_4
      - $(arg prefix)joint_5
      - $(arg prefix)joint_6
      - $(arg prefix)joint_7

  - name: "$(arg prefix)robotiq_2f_85_gripper_controller"
    action_ns: gripper_cmd
    default: True
    type: GripperCommand
    joints:
      - $(arg prefix)finger_joint