joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: "$(arg prefix)gen3_lite_joint_trajectory_controller"
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - $(arg prefix)joint_1
      - $(arg prefix)joint_2
      - $(arg prefix)joint_3
      - $(arg prefix)joint_4
      - $(arg prefix)joint_5
      - $(arg prefix)joint_6

  - name: "$(arg prefix)gen3_lite_2f_gripper_controller"
    action_ns: gripper_cmd
    default: True
    type: GripperCommand
    joints:
      - $(arg prefix)right_finger_bottom_joint