$(arg prefix)gen3_lite_2f_gripper_controller:
    type: position_controllers/GripperActionController
    joint: $(arg prefix)right_finger_bottom_joint
    action_monitor_rate: 100

gazebo_ros_control:
  pid_gains:
        $(arg prefix)right_finger_bottom_joint: {p: 10.0, i: 0.0, d: 0.0} 
        $(arg prefix)right_finger_tip_joint: {p: 1.0, i: 0.0, d: 0.0} 
        $(arg prefix)left_finger_bottom_joint: {p: 10.0, i: 0.0, d: 0.0} 
        $(arg prefix)left_finger_tip_joint: {p: 1.0, i: 0.0, d: 0.0}